### ISSUE TITLE
外部服务管理编辑完，提交出错

### ISSUE THREAD

**Issue by sunhongzhen** [AIPaaS/PaaS-FE-Platform-Portal#10]
外部服务管理编辑，所有项目都正确填写，点击提交：
出现错误 
 call remote service 'PcServiceSvc.saveOrUpdate()' error! Unknown column 'IP' in 'field list'

**Comment by guohong1** [comment]
这个是窦博他们组在数据库加字段了，你们需要在你们的数据库加上那些字段
如果加上还不行，就问问窦博那边有没有提交代码

**Comment by sunhongzhen** [comment]
pc_service表追加字段“IP”
