### ISSUE TITLE
【一般】用户门户》资源管理》租户资源配额，查看资源变更记录时，变更后资源状况显示有误。

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-FE-Platform-Portal#11]
实际显示为：C: 2个 ， M: D: 2 G ， D: 200 G
应该显示为：C: 2个 ， M: 2 G ， D: 200 G

**Comment by chen-xm** [comment]
1）、提测的功能说明： M: D:改为 M:
	2）、代码分支说明：develop
	3）、配置信息说明：无
	4）、数据库说明：无
	5）、是否有特殊的第三方软件安装：无
