### ISSUE TITLE
应用代码修改成与已有应用相同的代码，提交出错

### ISSUE THREAD

**Issue by sunhongzhen** [AIPaaS/PaaS-FE-Platform-Portal#13]
应用代码修改成与已有应用相同的代码，点击提交按钮
出现错误 
 call remote service 'PcAppSvc.saveOrUpdate()' error!  is exists code 'test_yingyong01'! 
建议：出提示“代码为xxx的应用已存在，请修改”

**Comment by sunhongzhen** [comment]
to bixiyan

**Comment by zhangqiang7** [comment]
已修复
