### ISSUE TITLE
服务代码修改成与已有服务相同的代码,提交出错

### ISSUE THREAD

**Issue by sunhongzhen** [AIPaaS/PaaS-FE-Platform-Portal#14]
服务代码修改成与已有服务相同的代码，点击提交按钮
出现错误： call remote service 'PcServiceSvc.saveOrUpdate()' error!  is exists code 'w_svc04'! 
建议：出提示“代码为xxx的服务已存在，请修改”

**Comment by sunhongzhen** [comment]
to liwenxian

**Comment by liwenxian** [comment]
已修改
