### ISSUE TITLE
在同一浏览器下，同一租户不同用户登录显示应用资源管理数据相同

### ISSUE THREAD

**Issue by sunhongzhen** [AIPaaS/PaaS-FE-Platform-Portal#17]
同一租户sunhz下：一用户sunhz01登录之后，在同一浏览器下，以不同的用户sunhz02登录时，会默认显示第一个用户sunhz01的应用资源管理数据信息。必须手动关闭浏览器，才能正常显示。数据缓存不能自动清理。

**Comment by yuanman001** [comment]
这可能是session失效的问题，可以再看看其他功能是否也存在同样的问题，一并处理。

**Comment by yuanman001** [comment]
已解决。

**Comment by yuanman001** [comment]
上次万文斌说过这个session的问题，他应该统一解决掉了，请再验证一下。

**Comment by guohong1** [comment]
已修改
