### ISSUE TITLE
特殊字符无校验

### ISSUE THREAD

**Issue by sunhongzhen** [AIPaaS/PaaS-FE-Platform-Portal#23]
部署管理->应用部署配置->应用容器清单->部署配置[开放服务] &&
部署管理->应用部署配置->应用容器清单->部署配置[其他参数]
添加参数时，没有对参数名，字符类型的校验。输入“@”，“~”等特殊字符。可以保存成功

**Comment by Mcbingchuan** [comment]
参数可以带这些字符  例如邮箱：XXXXX@XXX.COM
