### ISSUE TITLE
【一般】用户门户》部署管理》应用部署配置，新的应用进行容器定义，保存容器信息时，会更新pc_service表中之前已开放服务的数据。

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-FE-Platform-Portal#29]
用户门户》部署管理》应用部署配置，新的应用进行容器定义，保存容器信息时，会更新pc_service表中之前已开放服务的数据。
操作步骤：
1. 在应用1中，进行应用部署配置，定义容器20160314APP101，并开放为服务，点击保存。此时pc_service表中会增加一条镜像服务的记录，svc_code为yhj-yingyong01-20160314APP101

2.在应用2中，进行应用部署配置，定义容器20160314APP103，点击保存按钮，此时pc_service表中应用1操作时增加的记录，会被更新为应用2的数据：yhj-yingyong2-20160314APP103

**Comment by liwenxian** [comment]
已修复

**Comment by yuanhj3** [comment]
已解决
