### ISSUE TITLE
【一般】用户门户》部署管理》应用部署配置，调用/依赖步骤，添加服务时，应用服务列表展示不全

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-FE-Platform-Portal#32]
用户门户》部署管理》应用部署配置，调用/依赖步骤，添加服务时，应用服务列表展示不全

现象是：应用服务列表，只列了同一个应用下开放成外部服务的 应用服务，没有列出所属同一资源中心的其他应用服务

**Comment by liwenxian** [comment]
已修改

**Comment by yuanhj3** [comment]
外部服务和应用服务展示时，都要在同一个租户且同一资源中心下

**Comment by onle** [comment]
已修复
