### ISSUE TITLE
应用的运行权限问题

### ISSUE THREAD

**Issue by sunhongzhen** [AIPaaS/PaaS-FE-Platform-Portal#38]
应用运行管理中，一应用还没有申请资源，没进行部署配置，误点击了运行按钮，想停止没有停止按钮，运行按钮一直在转圈圈。未申请资源或者没有进行过部署配置的应用不应该有应用运行的权限，即：应用运行页面不应该显示

**Comment by Mcbingchuan** [comment]
已修改，未申请资源的应用点击部署后会有提示还未申请资源
