### ISSUE TITLE
应用定义的代码中有下划线出错

### ISSUE THREAD

**Issue by sunhongzhen** [AIPaaS/PaaS-FE-Platform-Portal#41]
应用代码中不能含有下划线“_”，后面生成的docker名，不识别。连字符“-”，因为不符合格式要求，无法输入，不确定是否可以。应用定义时，应用代码的字符限制需修改。

**Comment by bixiyan** [comment]
Unique identifier for the app consisting of a series of names separated by slashes. Each name must be at least 1 character and may only contain digits (0-9), dashes (-), dots (.), and lowercase letters (a-z). The name may not begin or end with a dash.

The allowable format is represented by the following regular expression ^(([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])$
光伟参考上面正则，给应用代码加上验证

**Comment by Mcbingchuan** [comment]
已修改
