### ISSUE TITLE
[严重]用户门户-部署管理-应用运行管理，启动运行时报错（原因：集群了3个地址，目前只支持一个地址））

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-Platform-Portal#49]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
登录-租户：chenhy0304 用户：chenhy 密码：123456
步骤：
1.登录系统
2.进入 部署管理-应用运行管理，启动运行时报错
原因：res_cluster_info 集群了3个地址，目前只支持一个地址
备注：用的是 程序部署的 那套资源

**Comment by riverxing** [comment]
1）、提测的功能说明：变更地址插入记录
2）、代码分支说明：develop
3）、配置信息说明：无
4）、数据库说明：无
5）、是否有特殊的第三方软件安装：无

**Comment by chenhy6** [comment]
验证通过
