### ISSUE TITLE
应用的显示未按数据权限分配

### ISSUE THREAD

**Issue by sunhongzhen** [AIPaaS/PaaS-FE-Platform-Portal#5]
前提：租户sunhz下有三个用户：sunhz01、sunhz02、sunhz03
用户sunzh01下定义三条应用：
定义的三条应用：
应用01
应用管理员：sunhz01
应用02
应用管理员：sunhz01，sunhz02
应用03
应用管理员：sunhz02

分别用用户sunhz02，sunhz03登录，三条应用全部显示
应用的显示未按数据权限分配
@wanwb

**Comment by guohong1** [comment]
同一个租户下边的不同用户的应用定义是可以查到的。
不同租户的是查不到的
