### ISSUE TITLE
数据格式提示信息不完整

### ISSUE THREAD

**Issue by sunhongzhen** [AIPaaS/PaaS-FE-Platform-Portal#6]
用户门户：部署管理->应用资源管理->
应用资源申请单->添加：
CPU个数：1.1111
内存大小：1.2222
存储大小：1.3333
点击提交。
①出的提示信息不完整“你必须使用此格式:”。
②CPU个数：1.1111 ，没有格式提示，提交之后为：1.11
@wanwb

**Comment by guohong1** [comment]
已修改。CPU个数：可保留1位小数，不可以超过8位数字。内存大小：8位整数。存储大小：8位整数

**Comment by guohong1** [comment]
修改的paas-wdep工程，代码已提交
