### ISSUE TITLE
点击外部服务管理出错

### ISSUE THREAD

**Issue by sunhongzhen** [AIPaaS/PaaS-FE-Platform-Portal#7]
用户门户：部署管理->外部服务管理：
出现错误
call remote service 'PcServiceSvc.queryPage()' error! Unknown column 'IP' in 'field list'
@wanwb

**Comment by guohong1** [comment]
这个是窦博他们组在数据库加字段了，你们也需要在你们的数据库加上这些字段
加上之后还报错的话，再看看他们的代码有没有提交
