### ISSUE TITLE
点击应用资源占用情况，出错

### ISSUE THREAD

**Issue by sunhongzhen** [AIPaaS/PaaS-FE-Platform-Portal#9]
用户门户：部署管理->应用部署配置：
第二个操作按钮，应用资源占用情况，
出现错误 
 call remote service 'PcAppSvc.queryAppNetZoneResInfo()' error! Unknown column 'IMAGE' in 'field list'
@wanwb

**Comment by guohong1** [comment]
这个问题在我这是没问题的，再构建一次再测一次吧

**Comment by sunhongzhen** [comment]
请指明具体需要构建哪几个工程？

**Comment by guohong1** [comment]
paas-wdep
